/*
	* PMDTestClass
	* @created: 2019/10/30 Truong Trang Ngoc Phuc
	* @modified:
*/
/*
	* testclass01
	* @created: 2019/10/30 Truong Trang Ngoc Phuc
	* @decription: Trong file test ko duoc su dung @isTest(seeAllData = true)
	* @modified:
*/
// @isTest(seeAllData= true)
@isTest(seeAllData= false)
/*
	* testclass06
	* @created: 2019/10/30 Truong Trang Ngoc Phuc
	* @decription: Phai su dung method Test.startTest(), Test.testStop de giam governor limits khi thuc thi test
	* @modified:
*/
// private class PMDTestClass {
private class PMDTestClassTest {
/*
	* testclass02
	* @created: 2019/10/30 Truong Trang Ngoc Phuc
	* @decription: Phai su dung method Test.startTest(), Test.testStop de giam governor limits khi thuc thi test
	* @modified:
*/
    // private static testMethod void testMethod02a(){}
    // private static testMethod void testMethod02b(){
    //     Test.startTest();
    //     Test.stopTest();
    // }

    // =================================================================

/*
	* testclass07
	* @created: 2019/10/30 Truong Trang Ngoc Phuc
	* @decription: Ten method test phai bat dau va chu test + Method muon test. Vidu: testSubString()
	* @modified:
*/
    // private static testMethod void method07() {
    //     Test.startTest();
    //     Test.stopTest();
    // }
    // private static testMethod void testMethod07() {
    //     Test.startTest();
    //     Test.stopTest();
    // }

}