/**
    * General-4
*/

public class test{
    /**
    * General-1
    */
    // private void GeneralRule1(){  

    // }

    /**
    * General-2
    */

    // public void general2(){
    //     // try{

    //     // }catch(Exception e){}
    // }

    /**
    * General-9
    */

    // private static Boolean isTest1;
    // private void general9(){
    //     isTest1 = true;
    //     Boolean hasTest2 = false;
    //     if(test2){}
    // }
    // private void test(){
    //     isTest1 = false;
    // }

    /**
    * General-12
    */

    // private void general12(){
    //     list<int> listTest = new list<int>();
    //     if(listTest.size() > 0){}
    //     if(listTest.isEmty()){}
    // }

    /**
    * General-13
    */

    // private int test1;
    // private void general13(){
    //     int test2 = 5;
    //     Test1 = true;
    // }
    // private void test2(){
    //     Test1 = true;
    // }

    /**
    * General-15
    */

    // public int a;
    // private void general151(){
    //     a = 5;
    // }
    //  private void general152(){
    //     a = 9;
    // }

    /**
    * General-16
    */

    // private static final string aaa = 'XXXXX';
    // private string b_b_b = 'XXXXX';
    // private void general161(){
    //     if(aaa == 'x'){}
    //     if(b_b_b == 'x'){}
    // }
    //  private void general162(){
    //     if(aaa == 'x'){}
    //     if(b_b_b == 'x'){}
    // }

    /**
    * General-17
    */

    private void general17(){
       Integer x = a+b;
    }
     

    /**
    * General-18
    */

    // private void general181(){
    //     int a = 0;
    //     int c = 1;
    //     int e = 2;
    //     general182(a, 'xxxxxx',c,
    //                 'sxsxsx',   e);
    // }
    // private void general182(int a, string b, int c,
    //                             string d,int e){
        
    // }

    /**
    * General-19
    */

    // private string gen19 = 'xxxx';
    // private void general191(){
    //     if(gen19.size() > 0){}
    //     if(gen19 == 'null'){}
    // }
    // private void general192(){
    //     //gen19 += 'asd';
    // }

    /**
    * General-20
    */

    // private void general20(){
    //     int ten = 10;
    //     for (Integer i = 0; i < ten; i++) {
    //         for (Integer j = 0; j < ten; j++) {
    //             for (Integer k = 0; k < ten; j++) {
                
    //             }
    //         }
    //     }
    // }

    /**
    * General-22
    */

    // private void general22(){
    //     int ten = 10;
    //     list<int> lst = new list<int>();
    //     for(int ad = 0; ad < ten; a++){}
    //     for(int ad : lst){}
    // }

    /**
    * General-24
    */
    
    // private void general241(){
    //     int ten = 10;
    //     for(int i = 0; i < ten; i++){
    //         general242();
    //     }
    // }

    // @future
    // private void general242(){

    // }

    /**
    * General-25
    */

    // private void general25(){
    //     Integer x = 0;
    //     if(true)
    //     x++;
    //     else 
    //     x--;    
    // }
    
    /**
    * General-26
    */

    // private void general26(){
    //     if(true){
    //         if(true){
    //             if(true){
    //                 if(true){
    //                     if(true){
    //                         if(true){

    //                         }
    //                     }
    //                 }
    //             }
    //         }
    //     }
    // }

    /**
    * General-33
    */

    // private void general33(){
    //     system.debug();
    // }

    /**
    * General-39
    */

    // private void general39(){
    //     int ten = 10;
    //     Account b;
    //     for(int i = 0; i < ten; i++){
    //         insert b;
    //     }
    //     for(int i = 0; i < ten; i++){
    //        testmethodxxx(); 
    //     }
    // }

    // private void testmethodxxx(){
    //     Account a;
    //     insert a;
    // }

    /**
    * General-43
    */

    // private void general43(){
    //     String strQuery = 'SELECT year FROM account LIMIT 1';
    //     int a;
    //     a = [SELECT year FROM account LIMIT 1];
    //     a = [SELECT year FROM account LIMIT 1];
    //     a = [SELECT year FROM account LIMIT 1];
    //     Database.query(strSOQL);
    //     Database.query(strSOQL);
    //     a = [SELECT year FROM account LIMIT 1];
    //     a = [SELECT year FROM account LIMIT 1];
    //     a = [SELECT year FROM account LIMIT 1];
    //     Database.query(strSOQL);
    //     Database.query(strSOQL);
    //     Database.query(strSOQL);
    // }

    /**
    * General-46
    */

    private void general46(){
        int ten = 10;
        int a;
        String strQuery = 'SELECT year FROM account LIMIT 1';
        Account b;
        for(int i = 0; i < ten; i++){
            Database.query(strSOQL);
            a = [SELECT year FROM account LIMIT 1];
        }
        for(int i = 0; i < ten; i++){
           testmethodxxxx(); 
        }
       
    }

    private void testmethodxxxx(){
        int a;
        String strQuery = 'SELECT year FROM account LIMIT 1';
        a = [SELECT year FROM account LIMIT 1];
        
    }

    /**
    * General-53
    */

    private void general53(){

    }

    /**
    * VisualPage-06
    */

    // private void visualpage06(){
    //     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter Account industry'));    
    // }
}